### ISSUE TITLE
Data Extract for Specialization Report

### ISSUE THREAD

**Issue by RajeevNagiri** [RajeevNagiri/DSG-Metrics-Project#3]
As per new req

**Comment by StuthiUrubail** [comment]
Hi Rajeev,
Data Extract for Specialization Report is completed. 
Below is the link
https://gssdev.in.ibm.com/t/DSG_Training/views/Specialization_Standard_Tables/SpecializationSummary?:embed=y&:showAppBanner=false&:showShareOptions=true&:display_count=no&:showVizHome=no
