### ISSUE TITLE
Data Extract for report

### ISSUE THREAD

**Issue by RajeevNagiri** [RajeevNagiri/DSG-Metrics-Project#4]
Do a data extract for Headcount,Attrition reports

**Comment by Keshavainbha123** [comment]
Hi Rajeev... I am getting error... as "This file was created by a newer version of Tableau. Please contact Tableau Software to upgrade your version.".... Not able to open tableau workbook....

**Comment by Keshavainbha123** [comment]
Problem rectified.. Extract .... In Progress

**Comment by Keshavainbha123** [comment]
Hi Rajeev,

Published extract Headcount workbook in server. Below is the link for your reference.

https://gssdev.in.ibm.com/t/DSG_Training/views/HC_StandTablesN_0/HCSummary?:embed=y&:showAppBanner=false&:showShareOptions=true&:display_count=no&:showVizHome=no

Regards,
Keshav
